"""update video table

Revision ID: 4ec20d78a345
Revises: e5c52e63bc97
Create Date: 2024-03-10 23:21:22.605461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ec20d78a345'
down_revision: Union[str, None] = 'e5c52e63bc97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('like_count', sa.Integer(), nullable=True), schema='youtube')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'like_count', schema='youtube')
    # ### end Alembic commands ###