"""add history tables

Revision ID: aea91967b824
Revises: c5aa6a1b6726
Create Date: 2024-03-17 16:35:27.268944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aea91967b824'
down_revision: Union[str, None] = 'c5aa6a1b6726'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.String(), nullable=True),
    sa.Column('follower_count', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('video_count', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['youtube.channels.channel_id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='youtube'
    )
    op.create_table('video_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['youtube.videos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='youtube'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_history', schema='youtube')
    op.drop_table('channel_history', schema='youtube')
    # ### end Alembic commands ###
