name: Release Project

on:
  push:
    tags:
      - "v*" # Триггер для версии, например, v1.0.0
  workflow_dispatch: # Ручной запуск workflow

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create ZIP archive
        run: |
          zip -r project-${GITHUB_REF_NAME#v}.zip . -x '*.git*'

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./project-${GITHUB_REF_NAME#v}.zip
          asset_name: project-${GITHUB_REF_NAME#v}.zip
          asset_content_type: application/zip

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            Release notes for ${{ github.ref_name }}
          draft: false
          prerelease: false
